language: node_js

node_js:
- 6

branches:
  only:
  - master

before_install:
- npm install -g gulp

install:
- cd doc && npm install
- cd .. && npm install

before_script:
- git config --global user.name 'Kaola Bot'
- git config --global user.email 'kaolabot@163.com'

script:
- gulp gen-doc

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../doc/public/* .
- git add -A .
- git commit -m 'Auto updated'
- git branch -m gh-pages
- git push -q -u origin gh-pages
